import numpy as np
import typing
import numpy.typing as npt

F = typing.TypeVar("F", np.float32, np.float64)

openmp_enabled: typing.Final[bool]

def adrt(a: npt.NDArray[F], /) -> npt.NDArray[F]: ...
def adrt_step(a: npt.NDArray[F], step: int, /) -> npt.NDArray[F]: ...
def iadrt(a: npt.NDArray[F], /) -> npt.NDArray[F]: ...
def bdrt(a: npt.NDArray[F], /) -> npt.NDArray[F]: ...
def bdrt_step(a: npt.NDArray[F], step: int, /) -> npt.NDArray[F]: ...
def num_iters(a: int, /) -> int: ...
def interp_to_cart(a: npt.NDArray[F], /) -> npt.NDArray[F]: ...
def press_fmg_restriction(a: npt.NDArray[F], /) -> npt.NDArray[F]: ...
def press_fmg_prolongation(a: npt.NDArray[F], /) -> npt.NDArray[F]: ...
def press_fmg_highpass(a: npt.NDArray[F], /) -> npt.NDArray[F]: ...
